### PR TITLE
Add time zone to deadline

### PR DESCRIPTION
**Pull request by fureigh**
I assume it's meant to be EST, but if you have a different time zone in mind let me know and I'll update this pull request.

Following up on #183.

### CODE REVIEW

**Comment by fureigh** [comment]
Thanks for the quick merge!

**Comment by chasingamy** [comment]
Note on this pull request: the East Coast is currently observing Daylight Savings Time, so the appropriate time zone should be EDT.

**Comment by konklone** [comment]
@parisj fixed in #185 =)

**Comment by chasingamy** [comment]
@konklone in readme.md yes, but not index.md. All good now either way!

**Pull request merged**
