### PR TITLE
Fix PDF link and add versioning to gem file 

### PR DESCRIPTION
**Pull request by PhilipBale**
(for example 3.5 Jekyll breaks build)

### CODE REVIEW

**Comment by AlvandSalehi** [comment]
@mattbailey0

**Review by ctubbsii — APPROVED** [review]
This change looks good. Somebody @WhiteHouse should merge this to fix the broken link, and fix the Jekyll build.

**Comment by IanLee1521** [comment]
May be something for @jcastle / @froi ?

**Comment by froi** [comment]
@IanLee1521 I can't work on anything for this repo.

**Comment by IanLee1521** [comment]
Thanks @AlvandSalehi !!

**Pull request closed without merging**
