### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by almubarakemterprises**

### CODE REVIEW

**Comment by IanLee1521** [comment]
Seems a bit spammy, and should be closed without merge cc/ @jcastle @froi

**Comment by froi** [comment]
I agree with @IanLee1521. I don't get what this PR is about.

**Comment by froi** [comment]
Shouldn't this be closed?

**Comment by IanLee1521** [comment]
@froi -- That's my vote. 👍

**Comment by ctubbsii** [comment]
Honestly, I'm a bit curious how long this issue will stay open before some technologist at the White House notices, and closes this pull request as spam, like they should have done when it was created 23 days ago.

**Comment by mattbailey0** [comment]
:robot:  👋 Closing; spam.

**Pull request closed without merging**
