### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by normanbrobinson**
Added accessibility (implying Access Board's IT Accessibility Standards; Section 508; WCAG Level AA) as that is a regulatory requirement for code that is developed with Government funds, and missing from this conversation. It is also a challenge that exist in Government-wide adoption of an open source policy.

### CODE REVIEW

**Comment by Scotchester** [comment]
:+1:

**Comment by RobertLRead** [comment]
Forgive my ignorance, @normanbrobinson , but how is that regulatory requirement a challenge to Government-wide adoption of an open source policy?  Without having read the statute you cite, it would seem independent/orthogonal.

**Comment by normanbrobinson** [comment]
Thanks for that observation @RobertLRead : It was to note that government-wide use of open source itself is a challenge, when accessibility is not necessarily developed into the software, when there is not general awareness in the open source arena, and when government is responsible for both selecting and ensuring accessibility is available to end-users (per Section 508). Agencies that choose to use open source technologies, face a real operational challenge when they have to ensure accessibility but it may not have even been an informal consideration by the developers or open source project owners. So any open source policy should address how agencies might choose to use technologies when it may meet the immediate business need, but not provide equal access and needs to be further developed to be inclusive of IT Accessibility standards.

**Comment by mhogeweg** [comment]
An accessibility assessment along with an evaluation of other functional/non-functional requirements fits well in the suggested steps for [procurement](https://sourcecode.cio.gov/Procurement/) (do alternative analysis and evaluate [COTS](http://dodcio.defense.gov/OpenSourceSoftwareFAQ.aspx#Q:_Is_open_source_software_commercial_software.3F_Is_it_COTS.3F) solutions before deciding on custom development).

**Comment by mattbailey0** [comment]
Thank you for your input - I'm closing this pull request given that the final language has now been released. Please feel free to reopen or create a new issue or pull if you'd like to continue the conversation!

**Pull request closed without merging**
